### ISSUE TITLE
--env tensorflow-1.4

### ISSUE THREAD

**Issue by AboHadi313** [Jwata/sushi_detector_dataset#2]
Hello,
Sorry for bothering you, but I want to make sure that there will be no errors during the training due to the version of python.
You used `--env tensorflow-1.4`, which is py3.6 on Floyd.
I did the same, and I used the .sh files you provided.
But in object_detection-0.1\object_detection\utils\visualization_utils_test.py line 148 there is a syntax error, although the server completed the installation correctly as it seems when I tested it using the run_test.sh file, which gave me the same output I get when running it on my pc.
line 148 is:
`print 'Writing output image %d to %s' % (i, output_file)`
Which is py2.7 not py3.6 nor py3.5 (I am using)

I ran your command with adding :py2:
```
floyd run --env tensorflow-1.4**_:py2_** \
  --data junji/datasets/sushi_detector/1:data \
  "bash ./floyd/setup.sh && cp -R /data/* /output && sh ./floyd/train.sh"
```
And I got no errors.
So, will it effect the training later on?

Maybe it looks like a newbie question (I am), but I'm working on my senior project, and I wanna make sure that everything is right before starting the training, I cannot waste hours of training because I'm on budget ! :(

**Comment by Jwata** [comment]
@AboHadi313 
Sorry for the late reply. And thank you for trying my repo.
I think it will work fine if the `run_test.sh` which runs `python -m object_detection.builders.model_builder_test` without errors.
If you worry about your steps, I recommend you to [train on your local machine](https://github.com/Jwata/sushi_detector_dataset#run-in-docker-container) to make sure if everything is working fine and then train further to Floydhub.

I hope this repo helped you.
