### ISSUE TITLE
Example project?

### ISSUE THREAD

**Issue by haemi** [Jwata/sushi_detector_dataset#3]
I'm really interested in the performance/fps - can you tell me something about it? Or can you provide the sushi-recognition example project? 🙂

**Comment by Jwata** [comment]
@haemi 
Thank you for your interest.
I recently wrote [a blog post](https://medium.com/@junjiwatanabe/how-to-build-real-time-object-recognition-ios-app-ca85c193865a) about the sushi recognition iOS app, in which you can find a demo video.

It takes around 0.1 sec to predict a frame on average. (meaning 9 fps)
But I think it can be improved by using Tensorflow Lite or/and converting the trained model to CoreML model.
