### ISSUE TITLE
中トロ

### ISSUE THREAD

**Issue by AYKFJSW** [Jwata/sushi_detector_dataset#4]
初めまして、突然失礼します.

ダウンロードさせていただいたところ
imageに中トロとサケが存在しないため
annotationsと照合するとエラーが出てしまいました

imageにあわせてannotationフォルダを変更し解決しましたが,
できれば中トロと残りのサケの画像もアップしてくださると嬉しいです
[annotations.zip](https://github.com/Jwata/sushi_detector_dataset/files/2353463/annotations.zip)

**Comment by Jwata** [comment]
@AYKFJSW 
画像ファイルはgiitignoreしたんですが、コミット済みの画像を消していませんでした。
Floydhubにdataset上げているので、こちらを参考にしてください。
https://www.floydhub.com/junji/datasets/sushi_detector/3/images
